media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: about
    label: About Page
    type: file
    path: about.markdown
    format: yaml-frontmatter
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Content
        type: rich-text